#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'migratoryBirds' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def migratoryBirds(arr):
    freq={}
    for i in arr:
        if i in freq:
            freq[i]+=1
        else:
            freq[i]=1
    
    
    birdType = sorted(list(freq.keys()))
    newFreq = sorted(list(freq.values()))
    maximum=max(newFreq)   
    pos=newFreq.index(maximum)
    x=newFreq.count(maximum)
    
    if x==1:
       
       return birdType[pos-1]
    else:
       temp=[]
       counter=0
       print(newFreq)
       for i in range(len(newFreq)):
          if newFreq[i]==maximum:
             temp.append(i)
             counter+=1
       t=temp[0] 
       for i in range(1,len(temp)):
          if t>temp[i]:
             t=temp[i]
    return t
          
                     
       
        
        
        
        
            
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
