#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'viralAdvertising' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#
'''
HackerLand Enterprise is adopting a new viral advertising strategy. When they launch a new product, they advertise it to exactly 5 people on social media.


'''
def viralAdvertising(n):
    shared=5
    liked=0
    no_of_friends=3
    for i in range(1,n+1):
        liked+=(shared//2)
        shared=(shared//2)*no_of_friends
        
    return liked


print(viralAdvertising(5))

        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()
